apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
  
data:
  default.conf: |
    server {
     listen       8000;
     listen  [::]:8000;
     server_name localhost;

     location /stub_status {
            stub_status on;
            allow 127.0.0.1;
      }


    }