apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
  labels:
    app: "homework"
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            server_name localhost;

            location / {
                proxy_pass http://backend;
            }

            location = /basic_status {
                stub_status;
            }
        }
    }