apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:0.9.0
        ports:
        - containerPort: 9113
        args:
        - '-nginx.scrape-uri=http://localhost:8000/stub_status'
        - '-web.listen-address=:9113'
      volumes:
      - name: config
        configMap:
          name: nginx-config