apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-prometheus-exporter
  namespace: homework
spec:
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  endpoints:
  - port: metrics
    interval: 15s