apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{.Values.namespace}}
  
data:
  default.conf: |
    server {
     listen       8000;
     listen  [::]:8000;
     server_name localhost;

     location / {
         root   /homework;
         index  index.html index.htm;
         autoindex on;
     }

    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: {{.Values.namespace}}
data:
  file: |
    homework kubernetes-volumes