apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: {{.Values.namespace}}
  labels:
    {{- include "homework-chart.labels" . | nindent 4 }}
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G