apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: {{.Values.namespace}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Values.namespace}}
  name: monitoring-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-rolebinding
  namespace: {{.Values.namespace}}
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: monitoring-role
  apiGroup: rbac.authorization.k8s.io