repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
 

releases:
  - name: my-kafka-dev
    namespace: dev
    chart: bitnami/kafka
    version: ""  # последняя доступная версия Kafka
    values:
      - replicaCount: 1
      - auth:
          enabled: false
      - service:
          externalTrafficPolicy: Local
    installed: true

  - name: my-kafka-prod
    namespace: prod
    chart: bitnami/kafka
    version: 28.0.4 
    values:
      - replicaCount: 5
      - image:
          tag: 3.5.2
      - auth:
          saslMechanism: sasl_plaintext
    installed: true